# Generated by Django 5.2 on 2025-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/No Product Image.svg', upload_to='product_images/'),
        ),
    ]
