# Generated by Django 5.2 on 2025-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meetup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meetup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meetup_place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
